[workspace.package]
version = "0.1.0"
authors = ["Victor M. Alvarez <vmalvarez@virustotal.com>"]
edition = "2021"

[workspace]
members = [
    "yara-x",
    "yara-x-cli",
    "yara-x-fmt",
    "yara-x-macros",
    "yara-x-parser",
    "yara-x-proto",
]

[workspace.dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.65"
ariadne = "0.1.5"
ascii_tree = "0.1.1"
bitmask = "0.5.0"
bitvec = "1.0.1"
bstr = "1.1.0"
criterion = "0.4.0"
globset = "0.4.9"
indenter = "0.3.3"
intaglio = "1.7.0"
lazy_static = "1.4.0"
line-span = "0.1.3"
memmap = "0.7.0"
num = "0.4.0"
pest = "2.5.2"
pest_derive = "2.5.2"
predicates = "2.1.4"
pretty_assertions = "1.3.0"
protobuf = "3.2.0"
protobuf-codegen = "3.2.0"
protobuf-parse = "3.2.0"
rustc-hash = "1.1.0"
thiserror = "1.0.38"
walrus = "0.19.0"
wasmtime = "3.0.1"
yaml-rust = "0.4.5"
yansi = "0.5.1"
yara-x = { path = "yara-x" }
yara-x-fmt = { path = "yara-x-fmt" }
yara-x-macros = { path = "yara-x-macros" }
yara-x-parser = { path = "yara-x-parser" }
yara-x-proto = { path = "yara-x-proto" }

[profile.release]
debug = 1