[package]
name = "yara-x-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "yr"
path = "src/main.rs"

[dependencies]
ascii_tree = { workspace = true }
ansi_term = { workspace = true }
anyhow = { workspace = true }
globset = { workspace = true }
yansi = { workspace = true }
yara-x = { workspace = true }
yara-x-parser = { workspace = true }
yara-x-fmt = { workspace = true }

clap = { version = "4.0.32", features=["cargo"] }
pprof = { version = "0.11", features = ["flamegraph"], optional=true }
walkdir = "2.3.2"
