branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
output-path: ./lcov.info
ignore:
  - "/home/runner/work/yara-x/yara-x/target/**/*"
  - "/home/runner/.cargo/registry/**/*"
