[package]
name = "yara-proto"
version = "0.1.0"
edition = "2021"
description = "Protocol buffer with options for YARA modules"

[dependencies]
protobuf = "3.2.0"

[build-dependencies]
protobuf =  "3.2.0"
protobuf-codegen =  "3.2.0"
protobuf-parse =  "3.2.0"