[package]
name = "yara-x-macros"
edition = "2021"
version = "0.1.0"

[lib]
name = "yara_macros"
proc-macro = true

[dependencies]
syn = {version = "1.0", features = ["derive", "parsing"]}
quote = "1.0"
proc-macro2 = "1.0.43"
convert_case = "0.6.0"