on: [push, pull_request]

name: Code coverage with grcov

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Build
      run: cargo build

    - name: Generate code coverage
      run: cargo llvm-cov --all-targets --features=compile-time-optimization,test_proto2-module,test_proto3-module --no-default-features --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: lcov.info
        fail_ci_if_error: true