on: [push, pull_request]

name: Code coverage with grcov

jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal

    - name: Execute tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features=compile-time-optimization,test_proto2-module,test_proto3-module --no-default-features
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests"

    - name: Gather coverage data
      id: coverage
      uses: actions-rs/grcov@v0.1
      with:
        coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
        config: .github/actions/grcov.yaml

    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ${{ steps.coverage.outputs.report }}

  grcov_finalize:
    runs-on: ubuntu-latest
    needs: grcov
    steps:
    - name: Coveralls finalization
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true