on: [push, pull_request]
name: Test suite

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo-test-args:
        - "--features test_proto2-module test_proto3-module"
        - "--features compile-time-optimization test_proto2-module test_proto3-module"
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.cargo-test-args }}
      env:
        RUSTFLAGS: -Awarnings  # Allow all warnings